
(function () {
var scripts = [{"deps":{"./assets/script/Clock":2,"./assets/script/CoinMgr":20,"./assets/script/Game":4,"./assets/script/Launch":6,"./assets/script/Main":7,"./assets/script/Settle":9,"./assets/script/SoundMgr":5,"./assets/script/Ball":8,"./assets/script/common/Global":12,"./assets/script/common/LocalData":14,"./assets/script/common/Module":3,"./assets/script/common/Move":10,"./assets/script/common/NodeFactory":11,"./assets/script/common/Utils":13,"./assets/script/common/EventMgr":21,"./assets/script/Basket":1,"./assets/customComponents/rank/scriipt/RankData":17,"./assets/customComponents/shop/script/ShopItem":19,"./assets/customComponents/shop/script/Shop":18,"./assets/customComponents/shop/script/ShopData":15,"./assets/customComponents/rank/scriipt/Rank":16},"path":"preview-scripts/__qc_index__.js"},{"deps":{"./Game":4,"./common/Utils":13,"./common/Module":3},"path":"preview-scripts/assets/script/Basket.js"},{"deps":{},"path":"preview-scripts/assets/script/Clock.js"},{"deps":{},"path":"preview-scripts/assets/script/common/Module.js"},{"deps":{"./Ball":8,"./Basket":1,"./Clock":2,"./CoinMgr":20,"./Settle":9,"./SoundMgr":5,"./common/Global":12,"./common/Module":3,"./common/NodeFactory":11,"./common/Utils":13,"./common/EventMgr":21},"path":"preview-scripts/assets/script/Game.js"},{"deps":{"./common/Module":3,"./common/Global":12},"path":"preview-scripts/assets/script/SoundMgr.js"},{"deps":{"./CoinMgr":20,"./Game":4,"./SoundMgr":5,"./common/Global":12,"./common/Module":3,"./common/EventMgr":21},"path":"preview-scripts/assets/script/Launch.js"},{"deps":{"./Game":4,"./Launch":6,"./common/Module":3,"./common/Global":12},"path":"preview-scripts/assets/script/Main.js"},{"deps":{"./Game":4,"./SoundMgr":5,"./common/Module":3,"./common/Utils":13,"./common/Global":12},"path":"preview-scripts/assets/script/Ball.js"},{"deps":{"./Game":4,"./Launch":6,"./SoundMgr":5,"./common/Module":3},"path":"preview-scripts/assets/script/Settle.js"},{"deps":{},"path":"preview-scripts/assets/script/common/Move.js"},{"deps":{},"path":"preview-scripts/assets/script/common/NodeFactory.js"},{"deps":{"./LocalData":14},"path":"preview-scripts/assets/script/common/Global.js"},{"deps":{},"path":"preview-scripts/assets/script/common/Utils.js"},{"deps":{},"path":"preview-scripts/assets/script/common/LocalData.js"},{"deps":{"../../../script/common/LocalData":14},"path":"preview-scripts/assets/customComponents/shop/script/ShopData.js"},{"deps":{},"path":"preview-scripts/assets/customComponents/rank/scriipt/Rank.js"},{"deps":{},"path":"preview-scripts/assets/customComponents/rank/scriipt/RankData.js"},{"deps":{"./ShopData":15,"./ShopItem":19,"../../../script/SoundMgr":5,"../../../script/common/NodeFactory":11,"../../../script/common/Module":3},"path":"preview-scripts/assets/customComponents/shop/script/Shop.js"},{"deps":{"./ShopData":15,"../../../script/CoinMgr":20,"../../../script/common/Utils":13,"../../../script/common/Global":12},"path":"preview-scripts/assets/customComponents/shop/script/ShopItem.js"},{"deps":{"./common/Global":12,"./common/EventMgr":21},"path":"preview-scripts/assets/script/CoinMgr.js"},{"deps":{},"path":"preview-scripts/assets/script/common/EventMgr.js"}];
var entries = ["preview-scripts/__qc_index__.js"];
var bundleScript = 'preview-scripts/__qc_bundle__.js';

/**
 * Notice: This file can not use ES6 (for IE 11)
 */
var modules = {};
var name2path = {};

// Will generated by module.js plugin
// var scripts = ${scripts};
// var entries = ${entries};
// var bundleScript = ${bundleScript};

if (typeof global === 'undefined') {
    window.global = window;
}

var isJSB = typeof jsb !== 'undefined';

function getXMLHttpRequest () {
    return window.XMLHttpRequest ? new window.XMLHttpRequest() : new ActiveXObject('MSXML2.XMLHTTP');
}

function downloadText(url, callback) {
    if (isJSB) {
        var result = jsb.fileUtils.getStringFromFile(url);
        callback(null, result);
        return;
    }

    var xhr = getXMLHttpRequest(),
        errInfo = 'Load text file failed: ' + url;
    xhr.open('GET', url, true);
    if (xhr.overrideMimeType) xhr.overrideMimeType('text\/plain; charset=utf-8');
    xhr.onload = function () {
        if (xhr.readyState === 4) {
            if (xhr.status === 200 || xhr.status === 0) {
                callback(null, xhr.responseText);
            }
            else {
                callback({status:xhr.status, errorMessage:errInfo + ', status: ' + xhr.status});
            }
        }
        else {
            callback({status:xhr.status, errorMessage:errInfo + '(wrong readyState)'});
        }
    };
    xhr.onerror = function(){
        callback({status:xhr.status, errorMessage:errInfo + '(error)'});
    };
    xhr.ontimeout = function(){
        callback({status:xhr.status, errorMessage:errInfo + '(time out)'});
    };
    xhr.send(null);
};

function loadScript (src, cb) {
    if (typeof require !== 'undefined') {
        require(src);
        return cb();
    }

    // var timer = 'load ' + src;
    // console.time(timer);

    var scriptElement = document.createElement('script');

    function done() {
        // console.timeEnd(timer);
        // deallocation immediate whatever
        scriptElement.remove();
    }

    scriptElement.onload = function () {
        done();
        cb();
    };
    scriptElement.onerror = function () {
        done();
        var error = 'Failed to load ' + src;
        console.error(error);
        cb(new Error(error));
    };
    scriptElement.setAttribute('type','text/javascript');
    scriptElement.setAttribute('charset', 'utf-8');
    scriptElement.setAttribute('src', src);

    document.head.appendChild(scriptElement);
}

function loadScripts (srcs, cb) {
    var n = srcs.length;

    srcs.forEach(function (src) {
        loadScript(src, function () {
            n--;
            if (n === 0) {
                cb();
            }
        });
    })
}

function formatPath (path) {
    let destPath = window.__quick_compile_project__.destPath;
    if (destPath) {
        let prefix = 'preview-scripts';
        if (destPath[destPath.length - 1] === '/') {
            prefix += '/';
        }
        path = path.replace(prefix, destPath);
    }
    return path;
}

window.__quick_compile_project__ = {
    destPath: '',

    registerModule: function (path, module) {
        path = formatPath(path);
        modules[path].module = module;
    },

    registerModuleFunc: function (path, func) {
        path = formatPath(path);
        modules[path].func = func;

        var sections = path.split('/');
        var name = sections[sections.length - 1];
        name = name.replace(/\.(?:js|ts|json)$/i, '');
        name2path[name] = path;
    },

    require: function (request, path) {
        var m, requestScript;

        path = formatPath(path);
        if (path) {
            m = modules[path];
            if (!m) {
                console.warn('Can not find module for path : ' + path);
                return null;
            }
        }

        if (m) {
            let depIndex = m.deps[request];
            // dependence script was excluded
            if (depIndex === -1) {
                return null;
            }
            else {
                requestScript = scripts[ m.deps[request] ];
            }
        }
        
        let requestPath = '';
        if (!requestScript) {
            // search from name2path when request is a dynamic module name
            if (/^[\w- .]*$/.test(request)) {
                requestPath = name2path[request];
            }

            if (!requestPath) {
                if (CC_JSB) {
                    return require(request);
                }
                else {
                    console.warn('Can not find deps [' + request + '] for path : ' + path);
                    return null;
                }
            }
        }
        else {
            requestPath = formatPath(requestScript.path);
        }

        let requestModule = modules[requestPath];
        if (!requestModule) {
            console.warn('Can not find request module for path : ' + requestPath);
            return null;
        }

        if (!requestModule.module && requestModule.func) {
            requestModule.func();
        }

        if (!requestModule.module) {
            console.warn('Can not find requestModule.module for path : ' + path);
            return null;
        }

        return requestModule.module.exports;
    },

    run: function () {
        entries.forEach(function (entry) {
            entry = formatPath(entry);
            var module = modules[entry];
            if (!module.module) {
                module.func();
            }
        });
    },

    load: function (cb) {
        var self = this;

        var srcs = scripts.map(function (script) {
            var path = formatPath(script.path);
            modules[path] = script;

            if (script.mtime) {
                path += ("?mtime=" + script.mtime);
            }
            return path;
        });

        console.time && console.time('load __quick_compile_project__');
        // jsb can not analysis sourcemap, so keep separate files.
        if (bundleScript && !isJSB) {
            downloadText(formatPath(bundleScript), function (err, bundleSource) {
                console.timeEnd && console.timeEnd('load __quick_compile_project__');
                if (err) {
                    console.error(err);
                    return;
                }

                let evalTime = 'eval __quick_compile_project__ : ' + srcs.length + ' files';
                console.time && console.time(evalTime);
                var sources = bundleSource.split('\n//------QC-SOURCE-SPLIT------\n');
                for (var i = 0; i < sources.length; i++) {
                    if (sources[i]) {
                        window.eval(sources[i]);
                        // not sure why new Function cannot set breakpoints precisely
                        // new Function(sources[i])()
                    }
                }
                self.run();
                console.timeEnd && console.timeEnd(evalTime);
                cb();
            })
        }
        else {
            loadScripts(srcs, function () {
                self.run();
                console.timeEnd && console.timeEnd('load __quick_compile_project__');
                cb();
            });
        }
    }
};

// Polyfill for IE 11
if (!('remove' in Element.prototype)) {
    Element.prototype.remove = function () {
        if (this.parentNode) {
            this.parentNode.removeChild(this);
        }
    };
}
})();
    